### ISSUE TITLE
Using PBIAPIClient interactively in PowerShell

### ISSUE THREAD

**Issue by fluxium** [gbrueckl/PowerBI.API.Client#1]
When using an instance of PBIAPIClient from PowerShell the Datasets collection is not populating as expected. I totally understand that the client was not explicitly designed for this use case but I was curious if it would work. The other collections in the PBIAPIClient seem to be populating correctly. It would be awesome if this client could be used interactively from PowerShell. I am working on automating our Power BI deployments and this library would help us out a lot. I am using PowerShell 5.1.

`try
{
    Add-Type -Path ".\gbrueckl.PowerBI.API.dll"
}
catch
{
    write-host $_.Exception.LoaderExceptions
}
$pbic = [gbrueckl.PowerBI.API.PBIAPIClient]($AppId)`

Inspecting `$pbic.Datasets` yields and an empty collection.

**Comment by gbrueckl** [comment]
I can reproduce your issue and will take a look!

**Comment by gbrueckl** [comment]
ok, so running the same code in a native C# console application actually works and returns the datasets correctly
Internally I am using the very same logic as for e.g Reports or Dashboards where the call to the API is made everytime the list-object is accessed. I assume this is somehow related to PowerShell.

**Comment by gbrueckl** [comment]
a set of PowerShell cmdlets for PowerBI was recently released:
https://powerbi.microsoft.com/en-us/blog/announcing-apis-and-powershell-cmdlets-for-power-bi-administrators/

it can be installed like this:
Install-Module -Name MicrosoftPowerBIMgmt

**Comment by gbrueckl** [comment]
I will more likely create a command line interface (CLI)

**Comment by gbrueckl** [comment]
there is also https://www.powershellgallery.com/packages/PowerBIPS
please us this if you are working with PowerShell - it has the same or extended functionality!

closing this issue now
