### ISSUE TITLE
Syncing to previously pushed dataset does not restore columns

### ISSUE THREAD

**Issue by abstractspoon** [gbrueckl/PowerBI.API.Client#11]
Hi Gerhard

After creating a dataset using the Sample_PushDataset, and then attempting to sync to it using the following function, the 'dataset' object is populated with the table that was created, but the table does not have any columns...

      private static void Test_SyncDataset(PBIAPIClient pbic)
      {
         string datasetName = "MyPushDataset";

         PBIDataset dataset = new PBIDataset(datasetName, PBIDefaultMode.Push);
         dataset.ParentPowerBIAPI = pbic;

         Console.WriteLine("Syncing to PowerBI Service ... ");
         dataset.SyncFromPowerBI(); // check if a Dataset with the same ID or Name already exists in the PowerBI-Service
         Console.WriteLine("Done!");
      }

**Comment by gbrueckl** [comment]
just checked the API again and it seems that a new functionality was added to also retrieve metadata for Push-datasets:
https://docs.microsoft.com/en-us/rest/api/power-bi/pushdatasets/datasets_gettables
will add this functionality in the near future and update you here!

**Comment by abstractspoon** [comment]
Many thx Gerhard.

>> new functionality was added to also retrieve metadata for Push-datasets:

TBH, I thought you were already supporting this:

```
        public string PBITable.ApiURL
        {
            get
            {
                if (ParentGroup == null)
                    return string.Format("/v1.0/myorg/datasets/{0}/tables/{1}", ParentDataset.Id, Name);
                else
                    return string.Format("/v1.0/myorg/groups/{0}/datasets/{1}/tables/{2}", ParentGroup.Id, ParentDataset.Id, Name);
            }
        }
```

**Comment by abstractspoon** [comment]
ps. I'm actually excited by the possibility of integrating your library into my app, hence my pushiness :)

**Comment by gbrueckl** [comment]
I just ran some tests and even though the docs state that the call to the tables API (https://docs.microsoft.com/en-us/rest/api/power-bi/pushdatasets/datasets_gettables) also returns columns and measures, it in fact only returns the name of the table

the JSON that I get returned is as follows:
```
{
  "@odata.context":"http://wabi-us-north-central-redirect.analysis.windows.net/v1.0/myorg/$metadata#tables","value":[
    {
      "name":"MySalesTable"
    }
  ]
}
```

once this is working correctly in the REST API, it will also return the columns, measures, etc. in the C# objects
