### ISSUE TITLE
When checking status getting back Status as "Unknown"

### ISSUE THREAD

**Issue by nssidhu** [gbrueckl/PowerBI.API.Client#12]
status = lst.Value.Where(c => c.RefreshType == "ViaApi" && c.StartTime != null && c.EndTime == null).FirstOrDefault().Status;

The value i Get back is "Unknown"

Secondly the problem i see is that i want Query the status of Currently running Refresh, does it return specific ID(like ExecutionID or something like which is latch on to and Query the status using ID).

I want to track progress of refresh which i triggered.
 var obj = client.Datasets.RefreshDataset(workspaceID, datasetID, refreshRequest);
Even in the above obj does not have enough details.

**Comment by gbrueckl** [comment]
regarding the status - the C# wrapper does not do anything on its own here, it just returns the values that were originally returned by the Power BI REST API. So you need to check what the status "Unknown" returned by the Power BI REST API actually means

To track the progress of a refresh, the only way would be to run 
<dataset>.LoadRefreshesFromPowerBI()
and then check in
<dataset>.Refreshes 
for the most recent refresh (or filter by ID)

**Comment by gbrueckl** [comment]
closing due to no further feedback
