### ISSUE TITLE
AddRowAPIEnabled does not work

### ISSUE THREAD

**Issue by chessIthaca** [gbrueckl/PowerBI.API.Client#13]
Hi there,

You have the flag addrowapienabled but it is not working as it should. I should be able to add rows to the toable yet the Table throws an exception because the type is "AsAzure" instead of push.

Otherwise great library!!! Keep up the good work!

**Comment by gbrueckl** [comment]
please make sure that the dataset was also created with the library (or with the API directly) with the appropriate settings (Push-Dataset)
You cannot just add rows to any Dataset

If the type is "AsAzure" then this actually means that the dataset connect to Azure Analysis Services and the type of a dataset cannot be changed after it was created

**Comment by chessIthaca** [comment]
Gerhard,

the dataset was created through the powerbi UI. But I get the same result
when creating it through the API, it gets returned as "Azure" the second
time I connect.

Carsten

Skype: hesscarsten
Tel: (607) 2790302
https://calendly.com/carstenhess

**Comment by gbrueckl** [comment]
When creating it, did you use PBIDefaultMode.Push?
Please see https://github.com/gbrueckl/PowerBI.API.Client/blob/master/SampleApplication/Program.cs line 173 onward where you can see a full sample of how to use the Push-API

**Comment by chessIthaca** [comment]
Yes I used push as the default mode.
Carsten

**Comment by gbrueckl** [comment]
and did you also try this when creating a whole new dataset and not using an existing?
can you run the sample code just to test whether it is a general bug or something specific to your environment/setup/code?

**Comment by gbrueckl** [comment]
closing due to no further feedback
