### ISSUE TITLE
How do I import PBIX files to an app workspace?

### ISSUE THREAD

**Issue by andreajeka** [gbrueckl/PowerBI.API.Client#14]
How do I import PBIX files to an app workspace instead of my workspace?

**Comment by gbrueckl** [comment]
There is a function called "ImportPBIX" which can be called from PBIAPIClient or any Group/Workspace object

**Comment by andreajeka** [comment]
Yes, I am aware of that function, but how do I set the Workspace?
I figured from the function I just need to set the Parent Group? Correct me if I am wrong.

```
PBIAPIClient pbic = new PBIAPIClient(ApplicationID, Username, Password);
pbic.ParentGroup = pbic.GetGroupByName("SampleWorkspace");
PBIImport import = pbic.ImportPBIX("report1", @"C:\pbix\test1.pbix", PBIImportConflictHandlerMode.CreateOrOverwrite);
```
I ran the above code but I didn't see the report being published in the target workspace or anywhere.

**Comment by andreajeka** [comment]
Thank you! I managed to call the function from the Group object.
