### ISSUE TITLE
Device certificate was not found for Cert Authorities

### ISSUE THREAD

**Issue by shrikantpandeydev** [gbrueckl/PowerBI.API.Client#15]
Hi Team, 

I am getting below error when trying to get access token from Azure Active Directory.

  | Name | Value | Type
-- | -- | -- | --
▶ | InnerException | {"Device Certificate was not found for Cert Authorities:OU=82dbaca4-3e81-46ca-9c73-0950c1eaca97,CN=MS-Organization-Access,DC=windows,DC=net"} | System.Exception {Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException}

Anyone knows the reason ?

**Comment by gbrueckl** [comment]
I would assume that this relates to some specifics in your AAD and you may only be allowed if you have a certain certificate installed on the local machine
do you know any specific restrictions/requirements your AAD has? Certificates, IP ranges, ...
Does it work if you connect to powerbi.com from the machine you get the error from?

**Comment by gbrueckl** [comment]
closing due to no further feedback
