### ISSUE TITLE
Receiving Azure errors trying to perform operations via your API wrapper :(

### ISSUE THREAD

**Issue by seedjay1** [gbrueckl/PowerBI.API.Client#16]
Been using your wrapper for a long time now, errors of the following sort only just recently started popping up when I try to push a model or rows to the service:

Error creating dataset: {"error":{"code":"GeneralException","message":"Failed to process dataset GetTables","target":"GetTables","details":[{"message":"Exception of type 'Microsoft.Cloud.Platform.Utils.AcquireLockTimeoutException' was thrown."}]}}

Any knowledge of this?

**Comment by gbrueckl** [comment]
have not seen this message before and as the code of the wrapper has not change I assume it is something related to the PBI service or your specific setup

is your dataset called "GetTables"? 
do you create the dataset using the wrapper? 
push, streaming or push/streaming dataset?

**Comment by seedjay1** [comment]
Yes the dataset is being created by the wrapper - push (FIFO).
The dataset is NOT called "GetTables" - the string "GetTables" does not exist in my code. I assumed it was some PowerBI/Azure method somehow sneaking into the exception message.

**Comment by gbrueckl** [comment]
I assume that they are changing something in the service which causes this issue. "GetTables" looks like an internal call to me which would return the tables of the dataset you publish or push rows to
Dont think that there is much I can do to fix this :(

**Comment by gbrueckl** [comment]
closing due to no further feedback
