### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by TerjeSolem** [gbrueckl/PowerBI.API.Client#19]
Hello.
How do I update one row in PB? Do I have to do it manually like this?

var newRow = new Dictionary<string, object>(); {logic}

 var oldRow = table.DataRows.FirstOrDefault(oldrow => oldrow.Id == newRow.Id);

            if (oldRow != null)
            {
                table.DataRows.Remove(oldRow);
            }

            table.DataRows.Add(newRow);

Would be nice with examples on basic crud operations on dataset, table, column, and row 😊👍

**Comment by gbrueckl** [comment]
unfortuantelly this is not how PowerBI works - you cannot update a single row
In fact, you can only add rows to a Streaming/PushStreaming dataset which is usually not what people use as it has a lot of limitations
to update the content of a PBI dataset you would need to change the source data (e.g. for SQL datasources, run an UPDATE on the SQL table) and the force a refresh of the PBI dataset
