### ISSUE TITLE
How to push new workspace up to pbi service?

### ISSUE THREAD

**Issue by seedjay1** [gbrueckl/PowerBI.API.Client#3]
I can add a new workspace/group locally, but I'm not seeing how to push it up to the service. Am I missing a method?

**Comment by gbrueckl** [comment]
you are right, currently does not work.
it seems the the functionality to work with groups/workspaces was recently extended to also support the creation of new groups
I will add this functionality also to the PBI API Client!

thanks for the hint

**Comment by seedjay1** [comment]
Heh no problem, looking forward to it! Basically I'm looking for a way to do PBI service tasks without managing all the httpclient hassles! A complete wrapper would be really great!

**Comment by gbrueckl** [comment]
I just added a new function to the PBI API Client to create groups:
PBIGroup myGroup = pbic.CreateGroup("MyTestGroup");
