### ISSUE TITLE
"Warning" publishing push dataset with formatstring/ishidden?

### ISSUE THREAD

**Issue by seedjay1** [gbrueckl/PowerBI.API.Client#6]
Basically your sample code - am I missing something here?

![image](https://user-images.githubusercontent.com/31414209/46263307-4bd8d080-c4c2-11e8-8779-5ff367db2ebc.png)

**Comment by seedjay1** [comment]
After some experimenting, it looks like whatever the LAST initialization (inline or traditional) is, doesn't take, and returns a message comparable to the above. All the prior property initializations get thru to pbi service dataset, just not the last one.

**Comment by seedjay1** [comment]
And it only happens when it's a NEW dataset being published. When it's overwriting one already there, the behavior does not manifest. Hope I'm not missing something stupid. :)

**Comment by gbrueckl** [comment]
Hi seedjay1,

you are right, seems like there was/is an issue with the columns. I tested it and could (most of the time) reproduce it - but it is not really consistent and I could not fix it directly

instead, I added a new function to the PBITable called AddColumn which should be used from now on to add new columns to a table

`PBITable salesTable = new PBITable("Facts"); // create a PBI table manually
            salesTable.AddColumn(new PBIColumn("ProductKey", PBIDataType.Int64) { IsHidden = true }); // hiding a column
            salesTable.AddColumn(new PBIColumn("SalesDate", PBIDataType.DateTime) { FormatString = "yyyy-MM-dd" }); // setting the Formatstring
            salesTable.AddColumn(new PBIColumn("Amount_BASE", PBIDataType.Double) { FormatString = "$ #,##0.00", IsHidden = true });`

this solves the issue then
I also updated all the samples

would be great if you can test it out!

regards,
-gerhard
